version: '3'
volumes:
  db_data:
  kafka-data:
  zk-txn-logs:
  zk-data:  
services:
  auth:
    depends_on: 
      - db
    build:
      context: auth/
      args:
        JWT_SECRET_KEY: 12345
        MONGO_DB_URL: mongodb://db:27017/mychat
        HTTP_PORT: 3000
    ports: 
      - "3001:3000" 
  chatroom:
    depends_on: 
      - db
      - auth
    build:
      context: chatroom/
      args:
        JWT_SECRET_KEY: 12345
        MONGO_DB_URL: mongodb://db:27017/mychat
        HTTP_PORT: 3000
    ports: 
      - "3002:3000"   
  db:
    image: mongo:4.2 
    volumes:
      - db_data:/data/db
  schema-registry: 
    image: confluentinc/cp-schema-registry:5.3.1
    ports: 
      - "8081:8081"
    environment: 
       SCHEMA_REGISTRY_HOST_NAME: schema-registry
       SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:32181
    depends_on:
      - zookeeper
  kafka:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    depends_on:
      - zookeeper
    environment: 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0      
    ports:
       - "9092:9092"
       - "29092:29092"
    volumes: 
      - kafka-data:/var/lib/kafka/data 
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    environment: 
      ZOOKEEPER_CLIENT_PORT: 32181
    volumes: 
      - zk-data:/var/lib/zookeeper/data 
      - zk-txn-logs:/var/lib/zookeeper/log    
  # control-center:
  #   image: confluentinc/cp-enterprise-control-center:5.3.1 
  #   ports: 
  #     - "9021:9021"
  #   environment: 
  #     CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:32181
  #     CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:29092'
  #     CONTROL_CENTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
  #     CONTROL_CENTER_REPLICATION_FACTOR: 1
  #   depends_on: 
  #     - zookeeper
  #     - kafka
  #     - schema-registry
  rest-proxy:
    image: confluentinc/cp-kafka-rest:5.3.1
    depends_on:
      - kafka
      - zookeeper
    environment: 
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_REST_LISTENERS: http://rest-proxy:8082
      KAFKA_REST_HOST_NAME: localhost
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
      KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS: 'GET,OPTIONS,HEAD,POST,PUT,DELETE' 
    ports: 
      - "8082:8082"


